<?php

/**
 * OneOfInterface
 *
 * PHP version 8.1
 *
 * @package  Dhl\Rest\Retoure\Model
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Returns API
 *
 * # Introduction ## Overview                  Note:   This is the specification of the DP-DHL Group Parcel DE Returns API. This web service allows business customers to create return labels on demand.  # Scenarios ## Main Scenario: Creating a returnlabel This is achieved by posting a return order to the URI '/rest/orders'. The service will respond with a return label. ## Querying to get receiver locations The single scenario supported by this service is the determination of the receiver's location. This is achieved by getting a location to the URI '/rest/locations'. The service will respond with a Receiver. # Technical Note on Authorization This API supports __two alternative ways__ to authorize yourself: 1. Combination of Apikey and Basic Authentication which you can provide with every call. 2. OAuth2 Password Flow: After having obtained your access token once, you provide this token as bearer token.   You can try it out here. More details can be found when clicking on \"Authorize\".
 *
 * The version of the OpenAPI document: 1.0.9
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dhl\Rest\Retoure\Model;

/**
 * Interface implemented by models generated from a `oneOf` schema.
 *
 * A `oneOf` schema is not represented by a value object; instead a value is one of the
 * composed member types. Classes implementing this interface only carry the metadata that
 * {@see ObjectSerializer::deserialize()} needs to resolve the concrete member type.
 *
 * @package Dhl\Rest\Retoure\Model
 * @author  OpenAPI Generator team
 */
interface OneOfInterface
{
    /**
     * List of the types a value of this `oneOf` schema may be. Each entry uses the same
     * notation as the values of {@see ModelInterface::openAPITypes()}.
     *
     * @return string[]
     */
    public static function getOneOfTypes(): array;

    /**
     * Name of the discriminator property used to resolve the concrete member type, or null
     * when the schema has no discriminator.
     *
     * @return string|null
     */
    public static function getOneOfDiscriminator(): ?string;

    /**
     * Mapping of discriminator values to the concrete member type. Empty when the schema has
     * no discriminator.
     *
     * @return array<string,string>
     */
    public static function getOneOfDiscriminatorMappings(): array;
}
